openapi: 3.0.0
info:
  title: Student API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /students:
    get:
      summary: 'get all student '
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
              examples:
                example-1:
                  value:
                    id: 0
                    name: string
                    age: 0
            application/xml:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value: {}
      operationId: get-students
      description: returns a list of students
      parameters: []
components:
  schemas:
    Student:
      title: Student
      x-examples:
        example-1:
          id: 0
          name: string
          age: null
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
